version: '3'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  airflow:
    image: apache/airflow:2.2.3
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
    depends_on:
      - db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
